export const enum GetAllFaqResponseCategoryEnumType {
  SERVICE = 'SERVICE',
  MEMBER = 'MEMBER',
  PRICE = 'PRICE',
  SOLUTION = 'SOLUTION',
  ETC = 'ETC',
  INCIDENT = 'INCIDENT',
}

export const enum PrintCostBracketTypeCategoryEnumType {
  SMALL = 'SMALL',
  PROFESSIONAL = 'PROFESSIONAL',
  BULK = 'BULK', // X-enumName Values Missing
}

export const enum CustomerReviewSolutionSolutionTypeEnumType {
  BRANDING_DESIGN = 'BRANDING_DESIGN',
  POP_DESIGN = 'POP_DESIGN',
  MARKET_ANALYSIS_BASED = 'MARKET_ANALYSIS_BASED',
  VMD_3D = 'VMD_3D',
  SAFETY_SIGNAGE = 'SAFETY_SIGNAGE',
  SEASONAL_PRINT = 'SEASONAL_PRINT',
  ALL_IN_ONE = 'ALL_IN_ONE',
  LOGISTICS_MANAGEMENT = 'LOGISTICS_MANAGEMENT',
  DIGITAL_VIDEO = 'DIGITAL_VIDEO',
  AR_PRINT = 'AR_PRINT',
  EX_SENSITIVITY_ANALYSIS = 'EX_SENSITIVITY_ANALYSIS',
  BUSINESS_CARD_SITE = 'BUSINESS_CARD_SITE',
  CORPORATE_PRINT_MALL = 'CORPORATE_PRINT_MALL',
  FRANCHISE_PRINT_MALL = 'FRANCHISE_PRINT_MALL', // X-enumName Values Missing
}

/**
 * 관련 분야
 */
export const enum GetCustomerReviewDetailTypeEnumType {
  VBD = 'VBD',
  POSM_POP = 'POSM_POP',
  DIARY_CALENDAR = 'DIARY_CALENDAR',
  SHOW_CARD = 'SHOW_CARD',
  DESIGN_PLANNING_SUBSCRIPTION = 'DESIGN_PLANNING_SUBSCRIPTION',
  BOOTH_EXHIBITION_CONSTRUCTION = 'BOOTH_EXHIBITION_CONSTRUCTION',
  PROMOTIONAL_ITEM = 'PROMOTIONAL_ITEM',
  GOODS_PRODUCTION = 'GOODS_PRODUCTION',
  PROMOTIONAL_MATERIAL = 'PROMOTIONAL_MATERIAL',
  SCAN_E_DOCUMENT = 'SCAN_E_DOCUMENT',
  SAFETY_SIGNAGE = 'SAFETY_SIGNAGE', // X-enumName Values Missing
}

export const enum GetSolutionExpertListParamsTypeEnumType {
  BRANDING_DESIGN = 'BRANDING_DESIGN',
  MARKET_ANALYSIS_BASED = 'MARKET_ANALYSIS_BASED',
  POP_DESIGN = 'POP_DESIGN',
  VMD_3D = 'VMD_3D',
  SAFETY_SIGNAGE = 'SAFETY_SIGNAGE',
  SEASONAL_PRINT = 'SEASONAL_PRINT',
  ALL_IN_ONE = 'ALL_IN_ONE',
  LOGISTICS_MANAGEMENT = 'LOGISTICS_MANAGEMENT',
  DIGITAL_VIDEO = 'DIGITAL_VIDEO',
  AR_PRINT = 'AR_PRINT',
  EX_SENSITIVITY_ANALYSIS = 'EX_SENSITIVITY_ANALYSIS',
  BUSINESS_CARD_SITE = 'BUSINESS_CARD_SITE',
  CORPORATE_PRINT_MALL = 'CORPORATE_PRINT_MALL',
  FRANCHISE_PRINT_MALL = 'FRANCHISE_PRINT_MALL',
}

export const enum GetSearchResponseParamsTypeEnumType {
  CUSTOMER_REVIEW = 'CUSTOMER_REVIEW',
  HELP_ARTICLE = 'HELP_ARTICLE',
  EXPERT = 'EXPERT',
}

export const enum GetAllHelpArticleParamsTypeEnumType {
  CONTRACT = 'CONTRACT',
  PRODUCTION = 'PRODUCTION',
  ORDER = 'ORDER',
  DELIVERY_INSTALLATION = 'DELIVERY_INSTALLATION',
  COST = 'COST',
  ETC = 'ETC',
}

export const enum GetAllFaqParamsCategoryEnumType {
  SERVICE = 'SERVICE',
  MEMBER = 'MEMBER',
  PRICE = 'PRICE',
  SOLUTION = 'SOLUTION',
  ETC = 'ETC',
  INCIDENT = 'INCIDENT',
}

export const enum GetAllCustomerReviewParamsTypeEnumType {
  VBD = 'VBD',
  POSM_POP = 'POSM_POP',
  DIARY_CALENDAR = 'DIARY_CALENDAR',
  SHOW_CARD = 'SHOW_CARD',
  DESIGN_PLANNING_SUBSCRIPTION = 'DESIGN_PLANNING_SUBSCRIPTION',
  BOOTH_EXHIBITION_CONSTRUCTION = 'BOOTH_EXHIBITION_CONSTRUCTION',
  PROMOTIONAL_ITEM = 'PROMOTIONAL_ITEM',
  GOODS_PRODUCTION = 'GOODS_PRODUCTION',
  PROMOTIONAL_MATERIAL = 'PROMOTIONAL_MATERIAL',
  SCAN_E_DOCUMENT = 'SCAN_E_DOCUMENT',
  SAFETY_SIGNAGE = 'SAFETY_SIGNAGE',
}

export const enum GetCustomerReviewRelationParamsTypeEnumType {
  VBD = 'VBD',
  POSM_POP = 'POSM_POP',
  DIARY_CALENDAR = 'DIARY_CALENDAR',
  SHOW_CARD = 'SHOW_CARD',
  DESIGN_PLANNING_SUBSCRIPTION = 'DESIGN_PLANNING_SUBSCRIPTION',
  BOOTH_EXHIBITION_CONSTRUCTION = 'BOOTH_EXHIBITION_CONSTRUCTION',
  PROMOTIONAL_ITEM = 'PROMOTIONAL_ITEM',
  GOODS_PRODUCTION = 'GOODS_PRODUCTION',
  PROMOTIONAL_MATERIAL = 'PROMOTIONAL_MATERIAL',
  SCAN_E_DOCUMENT = 'SCAN_E_DOCUMENT',
  SAFETY_SIGNAGE = 'SAFETY_SIGNAGE',
}
